ktor:
  deployment:
    port: "$PORT:8080"
  application:
    modules:
      - org.notahabr.MainKt.setup
      - org.notahabr.subsystem.DatabaseKt.dbModule
      - org.notahabr.feed.HabrKt.habrModule
      - org.notahabr.MainKt.facades
      - org.notahabr.MainKt.routes


database:
  url: $DATABASE_URL
  user: $DATABASE_USER
  password: $DATABASE_PASSWORD
